### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by avamsi** [skorokithakis/tbvaccine#1] opened 2016-08-29 12:56 UTC

**Comment by minchinweb** [comment] 2016-08-31 00:32
This may be as simple as importing and initializing colorama.

```
import colorama
colorama.init()
```

**Comment by skorokithakis** [comment] 2017-01-09 23:41
Ah, sorry, I just saw this now. I'm afraid I don't have a Windows machine, but any PRs for this would be welcome!

**Comment by frol** [comment] 2017-06-01 04:57
It seems that this is resolved with #7. Should this be closed now?

**Comment by szabolcsdombi** [comment] 2017-06-01 04:59
I can confirm **tbvaccine** works fine on Windows 10 x64

**Comment by skorokithakis** [comment] 2017-06-01 10:37
Yep, thank you! Can I ask how you found TBVaccine? I'm getting lots of comments today.

**Closed as completed by skorokithakis** 2017-06-01 10:37 UTC

**Comment by szabolcsdombi** [comment] 2017-06-01 11:03
I was waiting for my [ModernGL](https://github.com/cprogrammer1994/ModernGL) release to appear on the [pypi list](https://pypi.python.org/pypi)

I was browsing random packages while waiting. I opened **tbvaccine** as well. I found it **really really useful** for my development.

**Comment by frol** [comment] 2017-06-01 11:08
@skorokithakis I have noticed your issue with a suggestion of merge with better-exceptions project on their issue tracker, and since I have had an issue with better-exceptions working with Dask Distributed, I decided to give TBVaccine a try. BTW, TBVaccine worked OK, though the extra information doesn't seem to be sane/helpful #11.

**Comment by skorokithakis** [comment] 2017-06-01 12:05
I see, thank you! I'll get to #11 soon, although I don't use Distributed, so if you could take a look and see why it might be reporting weirdness, it would really help.

**Comment by frol** [comment] 2017-06-01 12:10
@skorokithakis Unfortunately, I don't have time at the moment, and to be honest, it is not a showstopper for me, so I am not sure I will be able to spend some time on digging into it soon. I reported the bug only with a hope that it will help you to improve TBVaccine (it might be that Dask case is not very specific and it only helped to identify a potential problem).

Cheers!

**Comment by skorokithakis** [comment] 2017-06-01 12:12
Ah, that's fine, thank you. The exception-getting code is pretty straightforward, so I don't think it's a general problem. It's more likely that Dask is doing something weird with exceptions, but I'll have a look anyway, just in case.
